version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      # CORREÇÃO 1: O nome do banco agora bate com o que a APP espera
      - POSTGRES_DB=encurtador_url
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/libs/postgresql/data

  app:
    build: .
    container_name: spring-encurtador
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # As variáveis aqui sobrescrevem o application.properties
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/encurtador_url
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  db-data: